### PR TITLE
Auxiliary coordinates for forecast period and forecast reference time

### PR DESCRIPTION
**Pull request by neishm**
Also, make --squash-forecasts the default behaviour.

### CODE REVIEW

**Comment by neishm** [comment]
I kept the name "forecast" for the forecast period, to be consistent with the "forecast" axis that's generated by --forecast-axis.  Also, the name "reftime" is used for the forecast reference time, just because it was shorter to type.  This can be changed if it causes problems with the netCDF tools.

**Comment by deacud** [comment]
Tested these changes on one of my files and everything was fine. I'm suggesting a few modifications (see the lines with comments below), but none of them is actually necessary to comply with CF.

float leadtime(time) ;                                                                                 # change forecast to leadtime
  leadtime:standard_name = "forecast_period" ;
  leadtime:units = "hours" ;
  leadtime:long_name = "Lead time (since forecast_reference_time)" ;    # add long_name attribute
double reftime(time) ;
  reftime:standard_name = "forecast_reference_time" ;
  reftime:units = "hours since 2015-01-31 00:00:00" ;
  reftime:calendar = "gregorian" ;                                                              # add calendar 
double time(time) ;
   time:standard_name = "time" ;                                                              # add standard_name 
   time:axis = "T" ;
   time:units = "hours since 2015-02-05 14:00:00" ;
   time:calendar = "gregorian" ;                                                                # add calendar
   time:long_name = "Validity time" ;                                                        # add long_name attribute

**Comment by deacud** [comment]
The variable names should not pose any problems - it is the standard names that actually matter.

**Comment by deacud** [comment]
How about making the reftime a scalar variable when the reference times are identical?

You can find an example in the CF documentation:
Example 5.12. Multiple forecasts from a single analysis (Section 5.7. Scalar Coordinate Variables)
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/cf-conventions.html#time-coordinate

**Comment by neishm** [comment]
Just applied the recommended updates to the metadata, will look into the scalar variable option.

**Comment by neishm** [comment]
Okay, reftime should now be a scalar when the values are all identical.

**Comment by deacud** [comment]
Tested this on a file. leadtime, reftime, time and metadate were all OK, and correctly read in IDV and Panoply.

**Pull request merged**
