### PR TITLE
Keep 'nomvar' as attribute if 'rename' is defined in metadata file

### PR DESCRIPTION
**Pull request by deacud**
I'm proposing that we keep nomvar as an attribute when the variable is renamed, so that we can still keep track of its origin. What do you think?

### CODE REVIEW

**Comment by neishm** [comment]
What about if `--minimal-metadata` was augmented to accept a list of attributes?  E.g., `--minimal-metadata=nomvar` would keep only the nomvar attribute, `--minimal-metadata=nomvar,etiket` would also keep the etiket, and `--minimal-metadata` without any arguments would keep _no_ RPN attributes (consistent with the current use of the option)?

**Comment by deacud** [comment]
That's a more general a preferable approach.

**Comment by deacud** [comment]
... and preferable ...

**Comment by deacud** [comment]
I've tested the modified option with two attributes (--minimal-metadata nomvar,typvar) on Shunli's test file containing time series data and it worked fine!

**Comment by neishm** [comment]
Hmmm... there's a small glitch where if you specify `--minimal-metadata` right before the RPN filename, it will interpret the filename as being the list of attribute names.  E.g., this will fail with the error "too few arguments":
```
fstd2nc --minimal-metadata infile.fst outfile.nc
```
One workaround is to separate the optional and positional arguments with `--`:
```
fstd2nc --minimal-metadata -- infile.fst outfile.nc
```
or pass in a blank argument to --minimal-metadata:
```
fstd2nc --minimal-metadata= infile.fst outfile.nc
```

I'll have to see if there's a way to patch this up in the script.  Maybe somehow tell argparse to only capture an argument for --minimal-metadata if it's a comma-separated list, or ignore it if it's a valid filename.

**Comment by deacud** [comment]
How about introducing options for the input and output files?

**Comment by neishm** [comment]
I was hoping to keep backwards-compatibility with how the input/output arguments are done now.  Maybe there could be a separate `--minimal-metadata-list` parameter which always expects a list of attributes, and the `--minimal-metadata` parameter could go back to taking no arguments?  That way there would be no ambiguity in the positional arguments...

**Comment by deacud** [comment]
This is a very good solution. I would suggest --rpnstd-metadata-list or something similar to clarify that a list of RPN standard file attributes is expected.

**Comment by deacud** [comment]
Tested the converter with --rpnstd-metadata-list 'nomvar,typvar' on a time series file and it worked as expected.

**Comment by neishm** [comment]
Great!  Will merge in the updates.

**Pull request merged**
